export const MOCK_COURSES = [
  {
    id: "python-masterclass",
    title: "The Complete Python Bootcamp From Zero to Hero in Python",
    description: "Learn Python like a Professional Start from the basics and go all the way to creating your own applications and games.",
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=800&auto=format&fit=crop",
    category: "Python",
    instructor: "Jose Portilla",
    rating: 4.8,
    reviewCount: 452102,
    price: 84.99,
    bestseller: true,
  },
  {
    id: "web-dev-2024",
    title: "The All-in-One Web Development Bootcamp",
    description: "Become a Full-Stack Web Developer with just ONE course. HTML, CSS, Javascript, Node, React, MongoDB, Web3 and DApps",
    thumbnail: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=800&auto=format&fit=crop",
    category: "Web Development",
    instructor: "Angela Yu",
    rating: 4.9,
    reviewCount: 320150,
    price: 89.99,
    bestseller: true,
  },
  {
    id: "excel-advanced",
    title: "Microsoft Excel - Excel from Beginner to Advanced",
    description: "Excel with this A-Z Microsoft Excel Course. Microsoft Excel 2013, 2016, 2019 and Office 365.",
    thumbnail: "https://images.unsplash.com/photo-1586717791821-3f44a563cc4c?q=80&w=800&auto=format&fit=crop",
    category: "Excel",
    instructor: "Kyle Pew",
    rating: 4.8,
    reviewCount: 210000,
    price: 59.99,
    bestseller: true,
  },
  {
    id: "javascript-modern",
    title: "The Complete JavaScript Course: From Zero to Expert!",
    description: "The modern JavaScript course for everyone! Master JavaScript with projects, challenges and theory.",
    thumbnail: "https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?q=80&w=800&auto=format&fit=crop",
    category: "JavaScript",
    instructor: "Jonas Schmedtmann",
    rating: 4.7,
    reviewCount: 156000,
    price: 79.99,
    bestseller: true,
  },
  {
    id: "aws-solutions-architect",
    title: "Ultimate AWS Certified Solutions Architect Associate 2024",
    description: "Full Practice Exam, CloudFormation, VPC, EC2, S3, Lambda, Route53, RDS, DynamoDB, ECS, Redshift, etc.",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop",
    category: "AWS Certification",
    instructor: "Stephane Maarek",
    rating: 4.7,
    reviewCount: 250000,
    price: 94.99,
    bestseller: true,
  },
  {
    id: "data-science-bootcamp",
    title: "The Data Science Course 2024: Complete Data Science Bootcamp",
    description: "Complete Data Science Training: Mathematics, Statistics, Python, Advanced Statistics in Python, Machine & Deep Learning.",
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800&auto=format&fit=crop",
    category: "Data Science",
    instructor: "365 Careers",
    rating: 4.6,
    reviewCount: 95000,
    price: 74.99,
    bestseller: false,
  },
];

export const MOCK_CATEGORIES = [
  { name: "Development", count: "3.2M learners", icon: "Code" },
  { name: "Business", count: "1.8M learners", icon: "Briefcase" },
  { name: "IT & Software", count: "2.1M learners", icon: "MonitorPlay" },
  { name: "Design", count: "1.4M learners", icon: "Palette" },
  { name: "Photography", count: "800k learners", icon: "Camera" },
  { name: "Audio & Music", count: "650k learners", icon: "Music" },
  { name: "Marketing", count: "1.1M learners", icon: "TrendingUp" },
  { name: "Finance", count: "900k learners", icon: "DollarSign" },
];
